#let terms = (
  (slug: "term-execution", title: [Execution], body: [One interpretation of a workflow for one input, with its own action progress, completed values, journal, and terminal evidence.]),
  (slug: "term-step-occurrence", title: [Step occurrence], body: [One structurally addressed use of a reusable step inside a workflow definition and execution.]),
  (slug: "term-workflow", title: [Workflow], body: [A reusable typed definition of dependency-connected steps with one input, output, business-error, and undo-error contract.]),
  (slug: "term-step", title: [Step], body: [A typed operation definition with its attempt, recovery, undo, timing, and optional persistence capabilities.]),
  (slug: "term-port", title: [Port], body: [An opaque typed reference to a dependency value within one workflow construction. _Avoid_: result name — names identify steps but do not transport native values.]),
  (slug: "term-step-address", title: [Step address], body: [The structural identity of a step occurrence: nested scope, name, and positive occurrence rank within that scope and name.]),
  (slug: "term-local-run", title: [Local run], body: [One execution of a workflow whose lifetime belongs to the process that starts it.]),
  (slug: "term-durable-execution", title: [Durable execution], body: [One saved execution identified within a storage and recoverable through a compatible workflow definition.]),
  (slug: "term-execution-handle", title: [Execution handle], body: [An opaque reference to a running local coordinator and its outcome-delivery ownership.]),
  (slug: "term-run-handle", title: [Run handle], body: [An opaque durable reference combining a persistence capability, storage, execution identifier, and drive configuration.]),
  (slug: "term-attempt", title: [Attempt], body: [One invocation of a step under its positive attempt number and fixed attempt budget.]),
  (slug: "term-effect-key", title: [Effect key], body: [An opaque action context containing stable idempotency identity, attempt identity, attempt number, and execution correlation.]),
  (slug: "term-compensation", title: [Compensation], body: [The failed-attempt decision that selects retry, replacement output, abort, or held uncertainty. _Avoid_: undo — undo addresses a known completed step.]),
  (slug: "term-undo", title: [Undo], body: [An application action intended to reverse a known completed step using its retained input, output, and own effect key.]),
  (slug: "term-undo-journal", title: [Undo journal], body: [The ordered completed-step records that retain undo capability and actual completion order.]),
  (slug: "term-settlement", title: [Settlement], body: [The complete retained evidence about undo, remaining known effects, interrupted actions, sibling failures, and unknown effects after admission stops.]),
  (slug: "term-unknown-effect", title: [Unknown effect], body: [An action whose effect status is unresolved because it crashed, timed out, was interrupted, or returned an application error classified as uncertain.]),
  (slug: "term-outcome", title: [Outcome], body: [The typed terminal report of completion, completion with unknown effects, failure, cancellation, or unresolved held evidence.]),
  (slug: "term-hold", title: [Hold], body: [A compensation decision retaining application evidence without authorizing retry or rollback of completed steps.]),
  (slug: "term-checkpoint", title: [Checkpoint], body: [A complete saved data representation of durable execution progress and its recovery authority.]),
  (slug: "term-persistence-capability", title: [Persistence capability], body: [The checked association of an existing workflow with root codecs, compatibility identity, and checkpoint limits.]),
  (slug: "term-compatibility-stamp", title: [Compatibility stamp], body: [A computed identity of the workflow structure, semantic versions, codecs, and declared recovery capabilities used to admit saved state.]),
  (slug: "term-codec", title: [Codec], body: [A versioned pair of fallible conversions between a native value and saved text.]),
  (slug: "term-storage", title: [Storage], body: [The atomic persistence port for saved bytes, execution claims, conditional commits, cancellation intent, and unfinished-execution discovery.]),
  (slug: "term-claim", title: [Claim], body: [The revocable execution ownership value identified by execution id, increasing generation, and adapter token. _Avoid_: process identity — a current claim can be used by another process.]),
  (slug: "term-revision", title: [Revision], body: [The increasing count of committed checkpoint changes for one durable execution.]),
  (slug: "term-resolver", title: [Resolver], body: [An application callback that establishes the result or absence of an interrupted admitted action without blindly repeating that action.]),
  (slug: "term-drive", title: [Drive], body: [One bounded runner attempt to advance a durable execution until it finishes, suspends, loses ownership, or exhausts its execution budget.]),
  (slug: "term-correlation", title: [Correlation], body: [The Sinal identity carried by an execution's action contexts and observations for joining application evidence.]),
  (slug: "term-report-receiver", title: [Report receiver], body: [The independent process retaining outcome-delivery responsibility for one short-lived invocation owner.]),
  (slug: "term-child", title: [Child], body: [An independently owned workflow execution attached to a parent through an explicit admission and observation contract.]),
  (slug: "term-compensation-authority", title: [Compensation authority], body: [The explicit owner-backed right to admit compensation of a successful child or completed execution.]),
  (slug: "term-approval", title: [Approval], body: [A suspended decision boundary retaining input and requiring an authenticated, revision-checked, deduplicated answer.]),
  (slug: "term-runtime-graph", title: [Runtime graph], body: [A graph authored after native compilation whose values and connections are checked against finite runtime data contracts.]),
  (slug: "term-published-graph", title: [Published graph], body: [An immutable executable runtime graph with resolved node versions, type parameters, configurations, and checked connections.]),
)
